### ISSUE TITLE
Error use: command not found

### ISSUE THREAD

**Issue by rijokr** [Decstasy/check_chrony#2]
Hi 
I have getting below mentioned syntax error.. could you please help to fix this issue 
./check_chrony.pl -w 1 -c 2
./check_chrony.pl: line 20: use: command not found
./check_chrony.pl: line 21: use: command not found
./check_chrony.pl: line 22: use: command not found
./check_chrony.pl: line 23: use: command not found
./check_chrony.pl: line 24: use: command not found
./check_chrony.pl: line 29: my: command not found
./check_chrony.pl: line 30: my: command not found
./check_chrony.pl: line 32: my: command not found
./check_chrony.pl: line 33: my: command not found
./check_chrony.pl: line 34: my: command not found
./check_chrony.pl: line 40: sub: command not found
./check_chrony.pl: line 44: print: command not found
./check_chrony.pl: line 45: syntax error near unexpected token `3'
./check_chrony.pl: line 45: `  exit(3);'
[root@# perl -v

This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 44 registered patches, see perl -V for more detail)

Copyright 1987-2012, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

**Comment by Decstasy** [comment]
Looks like the script was not interpreted by perl. I suspect the shebang line is not pointing to an executable binary on your system.
Please try: `perl check_chrony.pl -w 1 -c 2`
And replace the first line of the script `#!/usr/bin/env perl` with something like `#!/usr/bin/perl`. You can find out where the binary is with `type perl` or `which perl`.

**Comment by rijokr** [comment]
Hi Dennis
**Thank you so much for your support** 
Getting output using command  `perl check_chrony.pl -w 1 -c 2`  but .`/check_chrony.pl -w 1 -c 2` is not taking the shebang line 
and I'm added below line as shebang, after that the perl script running with ./  
```
#!/usr/bin/perl
eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}'
    if 0; # not running under some shell
```
referred from [https://stackoverflow.com/questions/12910744/why-should-the-shebang-line-always-be-the-first-line](url)
